encoding: utf-8
permalink: /blog/:categories/:year/:month/:day/:title.html
defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
prose:
  media: "files"
  siteurl: "https://gluxon.com"
